name: sunet-se

git:
  branch: main

builders:
  - docker
docker_tags:
  - stable

docker_name: sunet/sunet-se

extra_jobs:
  - name: sunet-se

    git:
      branch: staging

    builders:
      - docker
    docker_tags:
      - latest
