
git:
  branch: main

builders:
  - docker
docker_tags:
  - stable

docker_name: sunet/sunet-se-code

docker_dockerfile_dir: docker/

extra_jobs:
  - git:
      branch: staging

    builders:
      - docker
    docker_tags:
      - latest
