docker_name: sunet/sunet-se

builders:
  - docker

git:
  branch: main

docker_tags:
  - stable

triggers:
  github_push: false

extra_jobs:
  - name: sunet-se-code-test

    git:
      branch: dev

    docker_tags: []

    triggers:
      github_push: true
