name: sunet-se
docker_name: sunet/sunet-se
builders:
  - docker

git:
  branch: main

docker_tags:
  - stable

extra_jobs:
  - git:
      branch: dev

    docker_tags:
      - latest

    triggers:
      github_push: true
# test